import { useState, useEffect, useMemo } from 'react';                                                                                                                                                   
  import { PokemonCard } from '../components/PokemonCard';                                                                                                                                                
  import { pokemonApi, extractIdFromUrl } from '../services/pokemonApi';                                                                                                                                  
  import type { PokemonListItem } from '../types/pokemon';                                                                                                                                                
                                                                                                                                                                                                          
  interface PokemonWithType extends PokemonListItem {                                                                                                                                                     
    id: number;                                                                                                                                                                                           
    types: string[];                                                                                                                                                                                      
  }                                                                                                                                                                                                       
                                                                                                                                                                                                          
  const TYPE_CONFIG: Record<string, { color: string; bg: string }> = {                                                                                                                                    
    all: { color: 'text-gray-700', bg: 'bg-gray-200 hover:bg-gray-300' },                                                                                                                                 
    normal: { color: 'text-white', bg: 'bg-gray-400 hover:bg-gray-500' },                                                                                                                                 
    fire: { color: 'text-white', bg: 'bg-orange-500 hover:bg-orange-600' },                                                                                                                               
    water: { color: 'text-white', bg: 'bg-blue-500 hover:bg-blue-600' },                                                                                                                                  
    electric: { color: 'text-gray-900', bg: 'bg-yellow-400 hover:bg-yellow-500' },                                                                                                                        
    grass: { color: 'text-white', bg: 'bg-green-500 hover:bg-green-600' },                                                                                                                                
    ice: { color: 'text-gray-900', bg: 'bg-cyan-300 hover:bg-cyan-400' },                                                                                                                                 
    fighting: { color: 'text-white', bg: 'bg-red-700 hover:bg-red-800' },                                                                                                                                 
    poison: { color: 'text-white', bg: 'bg-purple-500 hover:bg-purple-600' },                                                                                                                             
    ground: { color: 'text-white', bg: 'bg-amber-600 hover:bg-amber-700' },                                                                                                                               
    flying: { color: 'text-white', bg: 'bg-indigo-400 hover:bg-indigo-500' },                                                                                                                             
    psychic: { color: 'text-white', bg: 'bg-pink-500 hover:bg-pink-600' },                                                                                                                                
    bug: { color: 'text-white', bg: 'bg-lime-600 hover:bg-lime-700' },                                                                                                                                    
    rock: { color: 'text-white', bg: 'bg-yellow-700 hover:bg-yellow-800' },                                                                                                                               
    ghost: { color: 'text-white', bg: 'bg-purple-700 hover:bg-purple-800' },                                                                                                                              
    dragon: { color: 'text-white', bg: 'bg-indigo-700 hover:bg-indigo-800' },                                                                                                                             
    dark: { color: 'text-white', bg: 'bg-gray-800 hover:bg-gray-900' },                                                                                                                                   
    steel: { color: 'text-white', bg: 'bg-gray-500 hover:bg-gray-600' },                                                                                                                                  
    fairy: { color: 'text-gray-900', bg: 'bg-pink-300 hover:bg-pink-400' },                                                                                                                               
  };                                                                                                                                                                                                      
                                                                                                                                                                                                          
  const POKEMON_TYPES = Object.keys(TYPE_CONFIG);                                                                                                                                                         
                                                                                                                                                                                                          
  export const PokemonList = () => {                                                                                                                                                                      
    const [pokemon, setPokemon] = useState<PokemonWithType[]>([]);                                                                                                                                        
    const [loading, setLoading] = useState(true);                                                                                                                                                         
    const [error, setError] = useState<string | null>(null);                                                                                                                                              
    const [searchQuery, setSearchQuery] = useState('');                                                                                                                                                   
    const [typeFilter, setTypeFilter] = useState('all');                                                                                                                                                  
                                                                                                                                                                                                          
    useEffect(() => {                                                                                                                                                                                     
      const fetchPokemon = async () => {                                                                                                                                                                  
        try {                                                                                                                                                                                             
          setLoading(true);                                                                                                                                                                               
          setError(null);                                                                                                                                                                                 
          const data = await pokemonApi.getList(150, 0);                                                                                                                                                  
                                                                                                                                                                                                          
          const pokemonWithTypes = await Promise.all(                                                                                                                                                     
            data.results.map(async (p) => {                                                                                                                                                               
              const id = extractIdFromUrl(p.url);                                                                                                                                                         
              try {                                                                                                                                                                                       
                const details = await pokemonApi.getById(id);                                                                                                                                             
                return {                                                                                                                                                                                  
                  ...p,                                                                                                                                                                                   
                  id,                                                                                                                                                                                     
                  types: details.types.map((t: any) => t.type.name),                                                                                                                                      
                };                                                                                                                                                                                        
              } catch {                                                                                                                                                                                   
                return { ...p, id, types: [] };                                                                                                                                                           
              }                                                                                                                                                                                           
            })                                                                                                                                                                                            
          );                                                                                                                                                                                              
                                                                                                                                                                                                          
          setPokemon(pokemonWithTypes);                                                                                                                                                                   
        } catch (err) {                                                                                                                                                                                   
          setError('Failed to load Pokemon. Please try again.');                                                                                                                                          
        } finally {                                                                                                                                                                                       
          setLoading(false);                                                                                                                                                                              
        }                                                                                                                                                                                                 
      };                                                                                                                                                                                                  
                                                                                                                                                                                                          
      fetchPokemon();                                                                                                                                                                                     
    }, []);                                                                                                                                                                                               
                                                                                                                                                                                                          
    const filteredPokemon = useMemo(() => {                                                                                                                                                               
      return pokemon.filter((p) => {                                                                                                                                                                      
        const matchesSearch = p.name.toLowerCase().includes(searchQuery.toLowerCase());                                                                                                                   
        const matchesType = typeFilter === 'all' || p.types.includes(typeFilter);                                                                                                                         
        return matchesSearch && matchesType;                                                                                                                                                              
      });                                                                                                                                                                                                 
    }, [pokemon, searchQuery, typeFilter]);                                                                                                                                                               
                                                                                                                                                                                                          
    if (loading) {                                                                                                                                                                                        
      return (                                                                                                                                                                                            
        <div className="flex flex-col justify-center items-center min-h-64 gap-4">                                                                                                                        
          <div className="w-16 h-16 border-4 border-red-500 border-t-transparent rounded-full animate-spin"></div>                                                                                        
          <div className="text-xl text-gray-600">Loading Pokemon...</div>                                                                                                                                 
        </div>                                                                                                                                                                                            
      );                                                                                                                                                                                                  
    }                                                                                                                                                                                                     
                                                                                                                                                                                                          
    if (error) {                                                                                                                                                                                          
      return (                                                                                                                                                                                            
        <div className="flex flex-col justify-center items-center min-h-64 gap-4">                                                                                                                        
          <div className="text-6xl">😢</div>                                                                                                                                                              
          <div className="text-xl text-red-600">{error}</div>                                                                                                                                             
          <button                                                                                                                                                                                         
            onClick={() => window.location.reload()}                                                                                                                                                      
            className="px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition"                                                                                                            
          >                                                                                                                                                                                               
            Try Again                                                                                                                                                                                     
          </button>                                                                                                                                                                                       
        </div>                                                                                                                                                                                            
      );                                                                                                                                                                                                  
    }                                                                                                                                                                                                     
                                                                                                                                                                                                          
    return (                                                                                                                                                                                              
      <div>                                                                                                                                                                                               
        {/* Search Bar */}                                                                                                                                                                                
        <div className="mb-6">                                                                                                                                                                            
          <div className="relative max-w-md">                                                                                                                                                             
            <input                                                                                                                                                                                        
              type="text"                                                                                                                                                                                 
              placeholder="Search Pokemon..."                                                                                                                                                             
              value={searchQuery}                                                                                                                                                                         
              onChange={(e) => setSearchQuery(e.target.value)}                                                                                                                                            
              className="w-full pl-10 pr-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-red-500 transition-colors"                                                            
            />                                                                                                                                                                                            
            <svg                                                                                                                                                                                          
              className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"                                                                                                                  
              fill="none"                                                                                                                                                                                 
              stroke="currentColor"                                                                                                                                                                       
              viewBox="0 0 24 24"                                                                                                                                                                         
            >                                                                                                                                                                                             
              <path                                                                                                                                                                                       
                strokeLinecap="round"                                                                                                                                                                     
                strokeLinejoin="round"                                                                                                                                                                    
                strokeWidth={2}                                                                                                                                                                           
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"                                                                                                                                           
              />                                                                                                                                                                                          
            </svg>                                                                                                                                                                                        
            {searchQuery && (                                                                                                                                                                             
              <button                                                                                                                                                                                     
                onClick={() => setSearchQuery('')}                                                                                                                                                        
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"                                                                                                   
              >                                                                                                                                                                                           
                ✕                                                                                                                                                                                         
              </button>                                                                                                                                                                                   
            )}                                                                                                                                                                                            
          </div>                                                                                                                                                                                          
        </div>                                                                                                                                                                                            
                                                                                                                                                                                                          
        {/* Type Filter Pills */}                                                                                                                                                                         
        <div className="mb-6">                                                                                                                                                                            
          <h3 className="text-sm font-semibold text-gray-600 mb-3">Filter by Type:</h3>                                                                                                                   
          <div className="flex flex-wrap gap-2">                                                                                                                                                          
            {POKEMON_TYPES.map((type) => {                                                                                                                                                                
              const config = TYPE_CONFIG[type];                                                                                                                                                           
              const isSelected = typeFilter === type;                                                                                                                                                     
              return (                                                                                                                                                                                    
                <button                                                                                                                                                                                   
                  key={type}                                                                                                                                                                              
                  onClick={() => setTypeFilter(type)}                                                                                                                                                     
                  aria-label={type === 'all' ? 'Filter by type' : undefined}                                                                                                                              
                  className={`                                                                                                                                                                            
                    px-4 py-2 rounded-full text-sm font-medium transition-all duration-200                                                                                                                
                    ${config.bg} ${config.color}                                                                                                                                                          
                    ${isSelected ? 'ring-2 ring-offset-2 ring-gray-400 scale-105' : 'opacity-70 hover:opacity-100'}                                                                                       
                  `}                                                                                                                                                                                      
                >                                                                                                                                                                                         
                  {type === 'all' ? '🎯 All' : type.charAt(0).toUpperCase() + type.slice(1)}                                                                                                              
                </button>                                                                                                                                                                                 
              );                                                                                                                                                                                          
            })}                                                                                                                                                                                           
          </div>                                                                                                                                                                                          
        </div>                                                                                                                                                                                            
                                                                                                                                                                                                          
        {/* Results Count */}                                                                                                                                                                             
        <div className="mb-4 text-sm text-gray-500">                                                                                                                                                      
          Showing {filteredPokemon.length} of {pokemon.length} Pokemon                                                                                                                                    
          {typeFilter !== 'all' && (                                                                                                                                                                      
            <span className="ml-2">                                                                                                                                                                       
              • Type: <span className="font-medium capitalize">{typeFilter}</span>                                                                                                                        
            </span>                                                                                                                                                                                       
          )}                                                                                                                                                                                              
          {searchQuery && (                                                                                                                                                                               
            <span className="ml-2">                                                                                                                                                                       
              • Search: <span className="font-medium">"{searchQuery}"</span>                                                                                                                              
            </span>                                                                                                                                                                                       
          )}                                                                                                                                                                                              
        </div>                                                                                                                                                                                            
                                                                                                                                                                                                          
        {/* Pokemon Grid or Empty State */}                                                                                                                                                               
        {filteredPokemon.length === 0 ? (                                                                                                                                                                 
          <div className="text-center py-16">                                                                                                                                                             
            <div className="text-6xl mb-4">🔍</div>                                                                                                                                                       
            <h3 className="text-xl font-semibold text-gray-700 mb-2">No Pokemon Found</h3>                                                                                                                
            <p className="text-gray-500 mb-4">Try adjusting your search or filter</p>                                                                                                                     
            <button                                                                                                                                                                                       
              onClick={() => {                                                                                                                                                                            
                setSearchQuery('');                                                                                                                                                                       
                setTypeFilter('all');                                                                                                                                                                     
              }}                                                                                                                                                                                          
              className="px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition"                                                                                                          
            >                                                                                                                                                                                             
              Clear Filters                                                                                                                                                                               
            </button>                                                                                                                                                                                     
          </div>                                                                                                                                                                                          
        ) : (                                                                                                                                                                                             
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">                                                                                                           
            {filteredPokemon.map((p) => (                                                                                                                                                                 
              <PokemonCard key={p.name} id={p.id} name={p.name} />                                                                                                                                        
            ))}                                                                                                                                                                                           
          </div>                                                                                                                                                                                          
        )}                                                                                                                                                                                                
      </div>                                                                                                                                                                                              
    );                                                                                                                                                                                                    
  };             